### ISSUE TITLE
Quiz and Assignments

### ISSUE THREAD

**Issue by johnDowee** [ZohebAbai/DSE220x#1]
Hello Zohaib, I am also auditing the course and found it very fruitful. I have a problem here, they have removed access to the questions for the auditors. I wonder if you have these saved with you and if you can share with me for practice.

Thank You

**Comment by hongjungg666** [comment]
I have the same problem, but I do think HW could help us a lot.

**Comment by ZohebAbai** [comment]
Apologies for the late reply. I hope you have already found it by now. Thanks for asking.
